# html lang
language: ch

# main menu navigation
menu:
  Home: /
#  Article: /article
#  BookCase: /bookcase
#  PrivateRoom: /room
#  Abbbbbbbout: /about

# stylesheets loaded in the <head>
stylesheets:
  - /css/Line.scss

# scripts loaded in the end of the body
scripts:
  - /js/Line.js
